variables:
  DOCKER_REGISTRY: 737247133335.dkr.ecr.us-east-1.amazonaws.com
  AWS_DEFAULT_REGION: us-east-1
  APP_NAME: mynode
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

publish:
  stage: build
  image: docker:20.10.24
  services:
    - docker:20.10.24-dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip aws-cli
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - aws --version
    - docker info
    - docker --version
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_ID .
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_ID
